name: Maven Build

on:
  workflow_call:
    inputs:
      java-version:
        required: false
        type: string
        default: 8
      sonar-project-key:
        required: true
        type: string
      sonar-project-name:
        required: true
        type: string

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Cache SonarCloud Packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Embed Mongo Distribution
        uses: actions/cache@v3
        with:
          path: ~/.embedmongo
          key: ${{ runner.os }}-mongo
          restore-keys: ${{ runner.os }}-mongo
      - name: Setup JDK ${{ inputs.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'adopt'
          cache: 'maven'
      - name: Build and Analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mvn -B test
          mvn -B jacoco:report sonar:sonar \
          -Dsonar.projectName=${{ inputs.sonar-project-name }} \
          -Dsonar.projectKey=${{ inputs.sonar-project-key }} 
