name: Maven Deploy

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      java-version:
        required: true
        type: string
        default: 8

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'adopt'
          cache: 'maven'
          server-id: sonatype-nexus-snapshots # Value of the distributionManagement/repository/id field of the pom.xml
          server-username: OSSRH_USERNAME # env variable for username in deploy
          server-password: OSSRH_PASSWORD # env variable for token in deploy
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }} # Value of the GPG private key to import
          gpg-passphrase: GPG_PASSPHRASE # env variable for GPG private key passphrase
      - name: Deploy to Nexus
        env:
          GPG_TTY: $(tty)
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mvn -B clean \
          org.projectlombok:lombok-maven-plugin:1.18.20.0:delombok \
          -Dlombok.sourceDirectory=src/main/java \
          -Dlombok.outputDirectory=target/delombok \
          -Dlombok.addOutputDirectory=false \
          -DsourceDirectory=target/delombok \
          -DskipTests=true deploy
