name: GitHub Package

on:
  workflow_call:
    inputs:
      repo:
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Test # Prevent deploying packages of part modules
        run: mvn test
      - name: Publish to GitHub Packages Apache Maven
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          mvn deploy -DskipTests=true \
          -Ddistribution.snapshots.id=github \
          -Ddistribution.snapshots.url=https://maven.pkg.github.com/${{ inputs.repo }} \
          -Ddistribution.release.id=github \
          -Ddistribution.release.url=https://maven.pkg.github.com/${{ inputs.repo }}
