name: GitHub Package

on:
  workflow_call:
    inputs:
      repo:
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: 'maven'
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }} # Value of the GPG private key to import
          gpg-passphrase: GPG_PASSPHRASE # env variable for GPG private key passphrase
      - name: Test # Prevent failures when partial modules are deployed
        run: mvn test
      - name: Publish to GitHub Packages Apache Maven
        env:
          GPG_TTY: $(tty)
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          GITHUB_TOKEN: ${{ github.token }}
        run: mvn -B deploy -DskipTests=true -Drepo=${{ inputs.repo }} -P github-package
